"""add imported_by to market_data

Revision ID: 0153c2a23f1d
Revises: 90a9ae34ee29
Create Date: 2026-08-16 16:52:03.327948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0153c2a23f1d'
down_revision: Union[str, Sequence[str], None] = '90a9ae34ee29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('imported_by', sa.Integer(), nullable=True))
    op.create_foreign_key('market_data_imported_by_fkey', 'market_data', 'users', ['imported_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('market_data_imported_by_fkey', 'market_data', type_='foreignkey')
    op.drop_column('market_data', 'imported_by')
    # ### end Alembic commands ###
